In [1]:
import geopandas as gpd
import matplotlib.pyplot as plt 
import numpy as np
import pandas as pd

from sklearn import preprocessing
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings('ignore')

In [4]:
def peek(df):
    display(df.head())
    display(len(df))

In [14]:
cbg_df = pd.read_csv('../data/cbg_attr_and_cluster_1021.csv')
cbg_df = cbg_df.rename(columns={
    'census_block_group': 'cbg',
    'Cluster': 'cluster',
    'Total Population': 'population',
    # Demographics.
    'Median Age': 'age',
    # Socioeconomics.
    'Median Household Income': 'income',
    'Percent Employed': 'employed_pct',
    'Percent Households with one or more people under 18 years': 'children_pct',
    'Percent Households with one or more people 60 years and over': 'seniors_pct',
    'Percent Household received Food Stamps/SNAP': 'snap_pct',
    'Percent Households Income in the past 12 months below poverty level': 'poverty_pct',
    'Percent over 25 with a bachelorâ€™s degree or higher': 'college_pct',
    'Percent over 25 without a high school diploma': 'no_hs_pct',
})
cbg_df = cbg_df[[
    'cbg',
    'cluster',
    'population',
    'income',
    'age',
    'employed_pct',
    'children_pct',
    'seniors_pct',
    'snap_pct',
    'poverty_pct',
    'college_pct',
    'no_hs_pct',
]]
cbg_df = cbg_df.sort_values(by=['cbg'])
cbg_df = cbg_df.set_index(cbg_df['cbg']).drop(columns=['cbg'])
# XXX
peek(cbg_df)

,cluster,population,income,age,employed_pct,children_pct,seniors_pct,snap_pct,poverty_pct,college_pct,no_hs_pct
cbg,,,,,,,,,,,
360050001001,2,6864,NaN,35.0,NaN,NaN,NaN,NaN,NaN,0.014873,0.515975
360050002001,2,1744,41968.0,40.2,0.762500,0.423913,0.541304,0.334783,0.326087,0.277975,0.246892
360050002002,2,1569,48523.0,28.9,0.860104,0.421384,0.425577,0.190776,0.144654,0.303395,0.243154
360050002003,3,1219,68060.0,42.2,0.985940,0.407407,0.585185,0.108642,0.024691,0.306054,0.137892
360050004001,3,598,NaN,40.3,1.000000,0.213740,0.492366,0.095420,0.312977,0.206989,0.174731

6221

In [15]:
cbg_df.to_json('../exports/cbg_attr_and_cluster_1115.json')